[2024-11-26T08:49:34.195+0000] {processor.py:161} INFO - Started process (PID=3502) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:49:34.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:49:34.197+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:49:34.196+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:49:34.199+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:49:34.198+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 24, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:49:34.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:49:34.212+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.020 seconds
[2024-11-26T08:50:04.563+0000] {processor.py:161} INFO - Started process (PID=3514) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:04.563+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:50:04.564+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:50:04.564+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:04.566+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:50:04.566+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 24, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:50:04.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:04.593+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.034 seconds
[2024-11-26T08:50:07.581+0000] {processor.py:161} INFO - Started process (PID=3515) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:07.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:50:07.583+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:50:07.583+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:07.585+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:50:07.585+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:50:07.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:07.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.026 seconds
[2024-11-26T08:50:37.983+0000] {processor.py:161} INFO - Started process (PID=3527) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:37.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:50:37.985+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:50:37.984+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:37.987+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:50:37.986+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:50:37.987+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:38.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.026 seconds
[2024-11-26T08:51:04.387+0000] {processor.py:161} INFO - Started process (PID=3539) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:51:04.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:51:04.406+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:51:04.406+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:51:04.408+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:51:04.408+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 21, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:51:04.408+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:51:04.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.044 seconds
[2024-11-26T08:51:34.792+0000] {processor.py:161} INFO - Started process (PID=3551) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:51:34.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:51:34.793+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:51:34.793+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:51:34.796+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:51:34.795+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 21, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:51:34.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:51:34.809+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.021 seconds
[2024-11-26T08:52:05.171+0000] {processor.py:161} INFO - Started process (PID=3563) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:52:05.185+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:52:05.186+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:52:05.186+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:52:05.188+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:52:05.187+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 21, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:52:05.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:52:05.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.104 seconds
[2024-11-26T08:52:35.536+0000] {processor.py:161} INFO - Started process (PID=3575) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:52:35.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:52:35.537+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:52:35.537+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:52:35.539+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:52:35.539+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 21, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:52:35.539+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:52:35.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.050 seconds
[2024-11-26T08:53:05.950+0000] {processor.py:161} INFO - Started process (PID=3587) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:53:05.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:53:05.952+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:53:05.952+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:53:05.954+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:53:05.953+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 21, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:53:05.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:53:05.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.028 seconds
[2024-11-26T08:53:35.325+0000] {processor.py:161} INFO - Started process (PID=3599) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:53:35.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:53:35.327+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:53:35.326+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:53:35.329+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:53:35.328+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:53:35.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:53:35.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.048 seconds
[2024-11-26T08:54:05.738+0000] {processor.py:161} INFO - Started process (PID=3611) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:54:05.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:54:05.759+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:54:05.759+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:54:05.761+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:54:05.760+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:54:05.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:54:05.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.054 seconds
